import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../assets/fonts/fonts.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-[100vh] bg-color_2">
          <div className="w-[1490px] mx-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
